/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuditLog
 */
export interface AuditLog {
    /**
     * Name of the action performed (e.g., CREATE, UPDATE, DELETE)
     * @type {string}
     * @memberof AuditLog
     */
    action?: string;
    /**
     * Timestamp when the audit log entry was created
     * @type {string}
     * @memberof AuditLog
     */
    createdAt?: string;
    /**
     * ID of the entity affected by the action
     * @type {string}
     * @memberof AuditLog
     */
    entityId?: string;
    /**
     * Type of entity affected by the action (e.g., User, Document)
     * @type {string}
     * @memberof AuditLog
     */
    entityType?: string;
    /**
     * Unique identifier for the audit log entry
     * @type {number}
     * @memberof AuditLog
     */
    id: number;
    /**
     * Outcome of the action (e.g., SUCCESS, FAILURE)
     * @type {string}
     * @memberof AuditLog
     */
    status: string;
    /**
     * ID of the user who performed the action (optional if system-generated)
     * @type {string}
     * @memberof AuditLog
     */
    userId?: string;
}

/**
 * Check if a given object implements the AuditLog interface.
 */
export function instanceOfAuditLog(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function AuditLogFromJSON(json: any): AuditLog {
    return AuditLogFromJSONTyped(json, false);
}

export function AuditLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'entityId': !exists(json, 'entityId') ? undefined : json['entityId'],
        'entityType': !exists(json, 'entityType') ? undefined : json['entityType'],
        'id': json['id'],
        'status': json['status'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function AuditLogToJSON(value?: AuditLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'createdAt': value.createdAt,
        'entityId': value.entityId,
        'entityType': value.entityType,
        'id': value.id,
        'status': value.status,
        'userId': value.userId,
    };
}

