/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuditLogCreate
 */
export interface AuditLogCreate {
    /**
     * Name of the action performed (e.g., CREATE, UPDATE, DELETE)
     * @type {string}
     * @memberof AuditLogCreate
     */
    action: string;
    /**
     * ID of the entity affected by the action
     * @type {string}
     * @memberof AuditLogCreate
     */
    entityId: string;
    /**
     * Type of entity affected by the action (e.g., User, Document)
     * @type {string}
     * @memberof AuditLogCreate
     */
    entityType: string;
    /**
     * Outcome of the action (e.g., SUCCESS, FAILURE)
     * @type {string}
     * @memberof AuditLogCreate
     */
    status: string;
    /**
     * ID of the user who performed the action (optional if system-generated)
     * @type {string}
     * @memberof AuditLogCreate
     */
    userId?: string;
}

/**
 * Check if a given object implements the AuditLogCreate interface.
 */
export function instanceOfAuditLogCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "entityId" in value;
    isInstance = isInstance && "entityType" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function AuditLogCreateFromJSON(json: any): AuditLogCreate {
    return AuditLogCreateFromJSONTyped(json, false);
}

export function AuditLogCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditLogCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'entityId': json['entityId'],
        'entityType': json['entityType'],
        'status': json['status'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function AuditLogCreateToJSON(value?: AuditLogCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'entityId': value.entityId,
        'entityType': value.entityType,
        'status': value.status,
        'userId': value.userId,
    };
}

