/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatHistoryUpdate
 */
export interface ChatHistoryUpdate {
    /**
     * JSON array of messages with role, content, timestamp.
     * @type {string}
     * @memberof ChatHistoryUpdate
     */
    messages?: string;
    /**
     * The model ID associated with the chat history.
     * @type {string}
     * @memberof ChatHistoryUpdate
     */
    modelId?: string;
    /**
     * The preset ID associated with the chat history.
     * @type {string}
     * @memberof ChatHistoryUpdate
     */
    presetId?: string;
}

/**
 * Check if a given object implements the ChatHistoryUpdate interface.
 */
export function instanceOfChatHistoryUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChatHistoryUpdateFromJSON(json: any): ChatHistoryUpdate {
    return ChatHistoryUpdateFromJSONTyped(json, false);
}

export function ChatHistoryUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatHistoryUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'messages': !exists(json, 'messages') ? undefined : json['messages'],
        'modelId': !exists(json, 'modelId') ? undefined : json['modelId'],
        'presetId': !exists(json, 'presetId') ? undefined : json['presetId'],
    };
}

export function ChatHistoryUpdateToJSON(value?: ChatHistoryUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'messages': value.messages,
        'modelId': value.modelId,
        'presetId': value.presetId,
    };
}

