/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatHistoryCreate
 */
export interface ChatHistoryCreate {
    /**
     * JSON array of messages with role, content, timestamp.
     * @type {string}
     * @memberof ChatHistoryCreate
     */
    messages: string;
    /**
     * The ID of the model used in the chat.
     * @type {string}
     * @memberof ChatHistoryCreate
     */
    modelId?: string;
    /**
     * The ID of the preset used in the chat.
     * @type {string}
     * @memberof ChatHistoryCreate
     */
    presetId?: string;
    /**
     * The ID of the user creating the chat history entry.
     * @type {string}
     * @memberof ChatHistoryCreate
     */
    userId: string;
}

/**
 * Check if a given object implements the ChatHistoryCreate interface.
 */
export function instanceOfChatHistoryCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "messages" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function ChatHistoryCreateFromJSON(json: any): ChatHistoryCreate {
    return ChatHistoryCreateFromJSONTyped(json, false);
}

export function ChatHistoryCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatHistoryCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'messages': json['messages'],
        'modelId': !exists(json, 'modelId') ? undefined : json['modelId'],
        'presetId': !exists(json, 'presetId') ? undefined : json['presetId'],
        'userId': json['userId'],
    };
}

export function ChatHistoryCreateToJSON(value?: ChatHistoryCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'messages': value.messages,
        'modelId': value.modelId,
        'presetId': value.presetId,
        'userId': value.userId,
    };
}

