/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChunkCreate
 */
export interface ChunkCreate {
    /**
     * The checksum of the chunk content.
     * @type {string}
     * @memberof ChunkCreate
     */
    checksum?: string;
    /**
     * The index of this chunk within the document.
     * @type {number}
     * @memberof ChunkCreate
     */
    chunkIndex: number;
    /**
     * The content of the chunk.
     * @type {string}
     * @memberof ChunkCreate
     */
    content: string;
    /**
     * The ID of the document this chunk belongs to.
     * @type {string}
     * @memberof ChunkCreate
     */
    documentId: string;
    /**
     * The number of tokens in the chunk.
     * @type {number}
     * @memberof ChunkCreate
     */
    tokenCount?: number;
}

/**
 * Check if a given object implements the ChunkCreate interface.
 */
export function instanceOfChunkCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chunkIndex" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "documentId" in value;

    return isInstance;
}

export function ChunkCreateFromJSON(json: any): ChunkCreate {
    return ChunkCreateFromJSONTyped(json, false);
}

export function ChunkCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChunkCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checksum': !exists(json, 'checksum') ? undefined : json['checksum'],
        'chunkIndex': json['chunkIndex'],
        'content': json['content'],
        'documentId': json['documentId'],
        'tokenCount': !exists(json, 'tokenCount') ? undefined : json['tokenCount'],
    };
}

export function ChunkCreateToJSON(value?: ChunkCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checksum': value.checksum,
        'chunkIndex': value.chunkIndex,
        'content': value.content,
        'documentId': value.documentId,
        'tokenCount': value.tokenCount,
    };
}

