/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentCreate
 */
export interface DocumentCreate {
    /**
     * The access control list group associated with the document.
     * @type {string}
     * @memberof DocumentCreate
     */
    aclGroup?: string;
    /**
     * The author of the document.
     * @type {string}
     * @memberof DocumentCreate
     */
    author?: string;
    /**
     * The type of document (e.g., PDF, DOCX).
     * @type {string}
     * @memberof DocumentCreate
     */
    docType?: string;
    /**
     * Indicates whether the document is currently active.
     * @type {boolean}
     * @memberof DocumentCreate
     */
    isActive?: boolean;
    /**
     * The URL where the document originated from.
     * @type {string}
     * @memberof DocumentCreate
     */
    sourceUrl?: string;
    /**
     * The title of the document.
     * @type {string}
     * @memberof DocumentCreate
     */
    title: string;
    /**
     * The version of the document.
     * @type {string}
     * @memberof DocumentCreate
     */
    version?: string;
}

/**
 * Check if a given object implements the DocumentCreate interface.
 */
export function instanceOfDocumentCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function DocumentCreateFromJSON(json: any): DocumentCreate {
    return DocumentCreateFromJSONTyped(json, false);
}

export function DocumentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aclGroup': !exists(json, 'aclGroup') ? undefined : json['aclGroup'],
        'author': !exists(json, 'author') ? undefined : json['author'],
        'docType': !exists(json, 'docType') ? undefined : json['docType'],
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
        'sourceUrl': !exists(json, 'sourceUrl') ? undefined : json['sourceUrl'],
        'title': json['title'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function DocumentCreateToJSON(value?: DocumentCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aclGroup': value.aclGroup,
        'author': value.author,
        'docType': value.docType,
        'isActive': value.isActive,
        'sourceUrl': value.sourceUrl,
        'title': value.title,
        'version': value.version,
    };
}

