/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Document
 */
export interface Document {
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    aclGroup?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    author?: string;
    /**
     * 
     * @type {Date}
     * @memberof Document
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    docType?: string;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof Document
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    sourceUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof Document
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    uploadedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    version?: string;
}

/**
 * Check if a given object implements the Document interface.
 */
export function instanceOfDocument(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function DocumentFromJSON(json: any): Document {
    return DocumentFromJSONTyped(json, false);
}

export function DocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Document {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aclGroup': !exists(json, 'aclGroup') ? undefined : json['aclGroup'],
        'author': !exists(json, 'author') ? undefined : json['author'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'docType': !exists(json, 'docType') ? undefined : json['docType'],
        'id': json['id'],
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
        'sourceUrl': !exists(json, 'sourceUrl') ? undefined : json['sourceUrl'],
        'title': json['title'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'uploadedBy': !exists(json, 'uploadedBy') ? undefined : json['uploadedBy'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function DocumentToJSON(value?: Document | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aclGroup': value.aclGroup,
        'author': value.author,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'docType': value.docType,
        'id': value.id,
        'isActive': value.isActive,
        'sourceUrl': value.sourceUrl,
        'title': value.title,
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'uploadedBy': value.uploadedBy,
        'version': value.version,
    };
}

