/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmbeddingUpdate
 */
export interface EmbeddingUpdate {
    /**
     * The ID of the chunk to which this vector belongs.
     * @type {string}
     * @memberof EmbeddingUpdate
     */
    chunkId: string;
    /**
     * JSON or stringified array of vector embeddings.
     * @type {string}
     * @memberof EmbeddingUpdate
     */
    vector: string;
}

/**
 * Check if a given object implements the EmbeddingUpdate interface.
 */
export function instanceOfEmbeddingUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chunkId" in value;
    isInstance = isInstance && "vector" in value;

    return isInstance;
}

export function EmbeddingUpdateFromJSON(json: any): EmbeddingUpdate {
    return EmbeddingUpdateFromJSONTyped(json, false);
}

export function EmbeddingUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chunkId': json['chunkId'],
        'vector': json['vector'],
    };
}

export function EmbeddingUpdateToJSON(value?: EmbeddingUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chunkId': value.chunkId,
        'vector': value.vector,
    };
}

