/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Embedding
 */
export interface Embedding {
    /**
     * 
     * @type {string}
     * @memberof Embedding
     */
    chunkId: string;
    /**
     * 
     * @type {Date}
     * @memberof Embedding
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Embedding
     */
    id: number;
    /**
     * JSON or stringified array of vector embeddings
     * @type {string}
     * @memberof Embedding
     */
    vector: string;
}

/**
 * Check if a given object implements the Embedding interface.
 */
export function instanceOfEmbedding(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chunkId" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "vector" in value;

    return isInstance;
}

export function EmbeddingFromJSON(json: any): Embedding {
    return EmbeddingFromJSONTyped(json, false);
}

export function EmbeddingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Embedding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chunkId': json['chunkId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'id': json['id'],
        'vector': json['vector'],
    };
}

export function EmbeddingToJSON(value?: Embedding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chunkId': value.chunkId,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'id': value.id,
        'vector': value.vector,
    };
}

