/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChatHistory } from './ChatHistory';
import {
    ChatHistoryFromJSON,
    ChatHistoryFromJSONTyped,
    ChatHistoryToJSON,
} from './ChatHistory';

/**
 * 
 * @export
 * @interface GetChatHistoryList200Response
 */
export interface GetChatHistoryList200Response {
    /**
     * 
     * @type {Array<ChatHistory>}
     * @memberof GetChatHistoryList200Response
     */
    items: Array<ChatHistory>;
    /**
     * Current page number
     * @type {number}
     * @memberof GetChatHistoryList200Response
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof GetChatHistoryList200Response
     */
    pageSize: number;
    /**
     * Total number of items available
     * @type {number}
     * @memberof GetChatHistoryList200Response
     */
    totalItems: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof GetChatHistoryList200Response
     */
    totalPages: number;
}

/**
 * Check if a given object implements the GetChatHistoryList200Response interface.
 */
export function instanceOfGetChatHistoryList200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalItems" in value;
    isInstance = isInstance && "totalPages" in value;

    return isInstance;
}

export function GetChatHistoryList200ResponseFromJSON(json: any): GetChatHistoryList200Response {
    return GetChatHistoryList200ResponseFromJSONTyped(json, false);
}

export function GetChatHistoryList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChatHistoryList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ChatHistoryFromJSON)),
        'page': json['page'],
        'pageSize': json['page_size'],
        'totalItems': json['total_items'],
        'totalPages': json['total_pages'],
    };
}

export function GetChatHistoryList200ResponseToJSON(value?: GetChatHistoryList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(ChatHistoryToJSON)),
        'page': value.page,
        'page_size': value.pageSize,
        'total_items': value.totalItems,
        'total_pages': value.totalPages,
    };
}

