/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Model } from './Model';
import {
    ModelFromJSON,
    ModelFromJSONTyped,
    ModelToJSON,
} from './Model';

/**
 * 
 * @export
 * @interface GetModelList200Response
 */
export interface GetModelList200Response {
    /**
     * 
     * @type {Array<Model>}
     * @memberof GetModelList200Response
     */
    items: Array<Model>;
    /**
     * Current page number
     * @type {number}
     * @memberof GetModelList200Response
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof GetModelList200Response
     */
    pageSize: number;
    /**
     * Total number of items available
     * @type {number}
     * @memberof GetModelList200Response
     */
    totalItems: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof GetModelList200Response
     */
    totalPages: number;
}

/**
 * Check if a given object implements the GetModelList200Response interface.
 */
export function instanceOfGetModelList200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalItems" in value;
    isInstance = isInstance && "totalPages" in value;

    return isInstance;
}

export function GetModelList200ResponseFromJSON(json: any): GetModelList200Response {
    return GetModelList200ResponseFromJSONTyped(json, false);
}

export function GetModelList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetModelList200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ModelFromJSON)),
        'page': json['page'],
        'pageSize': json['page_size'],
        'totalItems': json['total_items'],
        'totalPages': json['total_pages'],
    };
}

export function GetModelList200ResponseToJSON(value?: GetModelList200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(ModelToJSON)),
        'page': value.page,
        'page_size': value.pageSize,
        'total_items': value.totalItems,
        'total_pages': value.totalPages,
    };
}

