/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestionStep
 */
export interface IngestionStep {
    /**
     * 
     * @type {number}
     * @memberof IngestionStep
     */
    durationMs?: number;
    /**
     * 
     * @type {string}
     * @memberof IngestionStep
     */
    errorMessage?: string;
    /**
     * 
     * @type {Date}
     * @memberof IngestionStep
     */
    finishedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof IngestionStep
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof IngestionStep
     */
    jobId: string;
    /**
     * 
     * @type {Date}
     * @memberof IngestionStep
     */
    startedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof IngestionStep
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof IngestionStep
     */
    stepName: string;
}

/**
 * Check if a given object implements the IngestionStep interface.
 */
export function instanceOfIngestionStep(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "jobId" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "stepName" in value;

    return isInstance;
}

export function IngestionStepFromJSON(json: any): IngestionStep {
    return IngestionStepFromJSONTyped(json, false);
}

export function IngestionStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestionStep {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'durationMs': !exists(json, 'durationMs') ? undefined : json['durationMs'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'finishedAt': !exists(json, 'finishedAt') ? undefined : (new Date(json['finishedAt'])),
        'id': json['id'],
        'jobId': json['jobId'],
        'startedAt': !exists(json, 'startedAt') ? undefined : (new Date(json['startedAt'])),
        'status': json['status'],
        'stepName': json['stepName'],
    };
}

export function IngestionStepToJSON(value?: IngestionStep | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'durationMs': value.durationMs,
        'errorMessage': value.errorMessage,
        'finishedAt': value.finishedAt === undefined ? undefined : (value.finishedAt.toISOString()),
        'id': value.id,
        'jobId': value.jobId,
        'startedAt': value.startedAt === undefined ? undefined : (value.startedAt.toISOString()),
        'status': value.status,
        'stepName': value.stepName,
    };
}

