/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestionJobUpdate
 */
export interface IngestionJobUpdate {
    /**
     * An error message, if any, associated with the job.
     * @type {string}
     * @memberof IngestionJobUpdate
     */
    errorMessage?: string;
    /**
     * The timestamp when the job finished.
     * @type {Date}
     * @memberof IngestionJobUpdate
     */
    finishedAt?: Date;
    /**
     * The number of times the job has been retried.
     * @type {number}
     * @memberof IngestionJobUpdate
     */
    retryCount?: number;
    /**
     * The timestamp when the job started.
     * @type {Date}
     * @memberof IngestionJobUpdate
     */
    startedAt?: Date;
    /**
     * The current status of the job.
     * @type {string}
     * @memberof IngestionJobUpdate
     */
    status?: string;
    /**
     * The ID of the user associated with the job.
     * @type {string}
     * @memberof IngestionJobUpdate
     */
    userId?: string;
}

/**
 * Check if a given object implements the IngestionJobUpdate interface.
 */
export function instanceOfIngestionJobUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IngestionJobUpdateFromJSON(json: any): IngestionJobUpdate {
    return IngestionJobUpdateFromJSONTyped(json, false);
}

export function IngestionJobUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestionJobUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'finishedAt': !exists(json, 'finishedAt') ? undefined : (new Date(json['finishedAt'])),
        'retryCount': !exists(json, 'retryCount') ? undefined : json['retryCount'],
        'startedAt': !exists(json, 'startedAt') ? undefined : (new Date(json['startedAt'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function IngestionJobUpdateToJSON(value?: IngestionJobUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': value.errorMessage,
        'finishedAt': value.finishedAt === undefined ? undefined : (value.finishedAt.toISOString()),
        'retryCount': value.retryCount,
        'startedAt': value.startedAt === undefined ? undefined : (value.startedAt.toISOString()),
        'status': value.status,
        'userId': value.userId,
    };
}

