/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestionStepUpdate
 */
export interface IngestionStepUpdate {
    /**
     * The duration of the step in milliseconds.
     * @type {number}
     * @memberof IngestionStepUpdate
     */
    durationMs?: number;
    /**
     * Error message if the step failed.
     * @type {string}
     * @memberof IngestionStepUpdate
     */
    errorMessage?: string;
    /**
     * The date and time the step finished.
     * @type {Date}
     * @memberof IngestionStepUpdate
     */
    finishedAt?: Date;
    /**
     * The ID of the job this step belongs to.
     * @type {string}
     * @memberof IngestionStepUpdate
     */
    jobId?: string;
    /**
     * The date and time the step started.
     * @type {Date}
     * @memberof IngestionStepUpdate
     */
    startedAt?: Date;
    /**
     * The status of the step.
     * @type {string}
     * @memberof IngestionStepUpdate
     */
    status?: string;
    /**
     * The name of the step.
     * @type {string}
     * @memberof IngestionStepUpdate
     */
    stepName?: string;
}

/**
 * Check if a given object implements the IngestionStepUpdate interface.
 */
export function instanceOfIngestionStepUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IngestionStepUpdateFromJSON(json: any): IngestionStepUpdate {
    return IngestionStepUpdateFromJSONTyped(json, false);
}

export function IngestionStepUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestionStepUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'durationMs': !exists(json, 'durationMs') ? undefined : json['durationMs'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'finishedAt': !exists(json, 'finishedAt') ? undefined : (new Date(json['finishedAt'])),
        'jobId': !exists(json, 'jobId') ? undefined : json['jobId'],
        'startedAt': !exists(json, 'startedAt') ? undefined : (new Date(json['startedAt'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'stepName': !exists(json, 'stepName') ? undefined : json['stepName'],
    };
}

export function IngestionStepUpdateToJSON(value?: IngestionStepUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'durationMs': value.durationMs,
        'errorMessage': value.errorMessage,
        'finishedAt': value.finishedAt === undefined ? undefined : (value.finishedAt.toISOString()),
        'jobId': value.jobId,
        'startedAt': value.startedAt === undefined ? undefined : (value.startedAt.toISOString()),
        'status': value.status,
        'stepName': value.stepName,
    };
}

