/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestionStepCreate
 */
export interface IngestionStepCreate {
    /**
     * The duration of the step in milliseconds.
     * @type {number}
     * @memberof IngestionStepCreate
     */
    durationMs?: number;
    /**
     * An error message if the step failed.
     * @type {string}
     * @memberof IngestionStepCreate
     */
    errorMessage?: string;
    /**
     * The date and time when the step finished.
     * @type {Date}
     * @memberof IngestionStepCreate
     */
    finishedAt?: Date;
    /**
     * The ID of the job to which this step belongs.
     * @type {string}
     * @memberof IngestionStepCreate
     */
    jobId: string;
    /**
     * The date and time when the step started.
     * @type {Date}
     * @memberof IngestionStepCreate
     */
    startedAt?: Date;
    /**
     * The status of the step (e.g., pending, running, completed, failed).
     * @type {string}
     * @memberof IngestionStepCreate
     */
    status: string;
    /**
     * The name of the step.
     * @type {string}
     * @memberof IngestionStepCreate
     */
    stepName: string;
}

/**
 * Check if a given object implements the IngestionStepCreate interface.
 */
export function instanceOfIngestionStepCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "jobId" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "stepName" in value;

    return isInstance;
}

export function IngestionStepCreateFromJSON(json: any): IngestionStepCreate {
    return IngestionStepCreateFromJSONTyped(json, false);
}

export function IngestionStepCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestionStepCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'durationMs': !exists(json, 'durationMs') ? undefined : json['durationMs'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'finishedAt': !exists(json, 'finishedAt') ? undefined : (new Date(json['finishedAt'])),
        'jobId': json['jobId'],
        'startedAt': !exists(json, 'startedAt') ? undefined : (new Date(json['startedAt'])),
        'status': json['status'],
        'stepName': json['stepName'],
    };
}

export function IngestionStepCreateToJSON(value?: IngestionStepCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'durationMs': value.durationMs,
        'errorMessage': value.errorMessage,
        'finishedAt': value.finishedAt === undefined ? undefined : (value.finishedAt.toISOString()),
        'jobId': value.jobId,
        'startedAt': value.startedAt === undefined ? undefined : (value.startedAt.toISOString()),
        'status': value.status,
        'stepName': value.stepName,
    };
}

