/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestionJobCreate
 */
export interface IngestionJobCreate {
    /**
     * The ID of the document being processed.
     * @type {string}
     * @memberof IngestionJobCreate
     */
    documentId: string;
    /**
     * An error message if the process failed.
     * @type {string}
     * @memberof IngestionJobCreate
     */
    errorMessage?: string;
    /**
     * The timestamp when the process finished.
     * @type {Date}
     * @memberof IngestionJobCreate
     */
    finishedAt?: Date;
    /**
     * The number of times the process has been retried.
     * @type {number}
     * @memberof IngestionJobCreate
     */
    retryCount?: number;
    /**
     * The timestamp when the process started.
     * @type {Date}
     * @memberof IngestionJobCreate
     */
    startedAt?: Date;
    /**
     * The current status of the process.
     * @type {string}
     * @memberof IngestionJobCreate
     */
    status: string;
    /**
     * The ID of the user who initiated the process.
     * @type {string}
     * @memberof IngestionJobCreate
     */
    userId?: string;
}

/**
 * Check if a given object implements the IngestionJobCreate interface.
 */
export function instanceOfIngestionJobCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "documentId" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function IngestionJobCreateFromJSON(json: any): IngestionJobCreate {
    return IngestionJobCreateFromJSONTyped(json, false);
}

export function IngestionJobCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestionJobCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentId': json['documentId'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'finishedAt': !exists(json, 'finishedAt') ? undefined : (new Date(json['finishedAt'])),
        'retryCount': !exists(json, 'retryCount') ? undefined : json['retryCount'],
        'startedAt': !exists(json, 'startedAt') ? undefined : (new Date(json['startedAt'])),
        'status': json['status'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function IngestionJobCreateToJSON(value?: IngestionJobCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documentId': value.documentId,
        'errorMessage': value.errorMessage,
        'finishedAt': value.finishedAt === undefined ? undefined : (value.finishedAt.toISOString()),
        'retryCount': value.retryCount,
        'startedAt': value.startedAt === undefined ? undefined : (value.startedAt.toISOString()),
        'status': value.status,
        'userId': value.userId,
    };
}

