/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * JWT access token
     * @type {string}
     * @memberof LoginResponse
     */
    accessToken?: string;
    /**
     * Expiration time in seconds
     * @type {number}
     * @memberof LoginResponse
     */
    expiresIn?: number;
    /**
     * Token to refresh access
     * @type {string}
     * @memberof LoginResponse
     */
    refreshToken?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    tokenType?: string;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'access_token') ? undefined : json['access_token'],
        'expiresIn': !exists(json, 'expires_in') ? undefined : json['expires_in'],
        'refreshToken': !exists(json, 'refresh_token') ? undefined : json['refresh_token'],
        'tokenType': !exists(json, 'token_type') ? undefined : json['token_type'],
    };
}

export function LoginResponseToJSON(value?: LoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'expires_in': value.expiresIn,
        'refresh_token': value.refreshToken,
        'token_type': value.tokenType,
    };
}

