/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Model for updating a model.
 * @export
 * @interface ModelUpdate
 */
export interface ModelUpdate {
    /**
     * The category this model belongs to.
     * @type {string}
     * @memberof ModelUpdate
     */
    categoryId?: string;
    /**
     * A more detailed explanation of the model.
     * @type {string}
     * @memberof ModelUpdate
     */
    description?: string;
    /**
     * The name of the model.
     * @type {string}
     * @memberof ModelUpdate
     */
    name?: string;
}

/**
 * Check if a given object implements the ModelUpdate interface.
 */
export function instanceOfModelUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelUpdateFromJSON(json: any): ModelUpdate {
    return ModelUpdateFromJSONTyped(json, false);
}

export function ModelUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function ModelUpdateToJSON(value?: ModelUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categoryId': value.categoryId,
        'description': value.description,
        'name': value.name,
    };
}

