/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelCreate
 */
export interface ModelCreate {
    /**
     * The category ID to which this model belongs.
     * @type {string}
     * @memberof ModelCreate
     */
    categoryId: string;
    /**
     * A more detailed explanation of the model.
     * @type {string}
     * @memberof ModelCreate
     */
    description?: string;
    /**
     * Name of the model.
     * @type {string}
     * @memberof ModelCreate
     */
    name: string;
}

/**
 * Check if a given object implements the ModelCreate interface.
 */
export function instanceOfModelCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "categoryId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ModelCreateFromJSON(json: any): ModelCreate {
    return ModelCreateFromJSONTyped(json, false);
}

export function ModelCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
    };
}

export function ModelCreateToJSON(value?: ModelCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categoryId': value.categoryId,
        'description': value.description,
        'name': value.name,
    };
}

