/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PresetCreate
 */
export interface PresetCreate {
    /**
     * The configuration details for the environment preset (e.g., JSON or YAML string).
     * @type {string}
     * @memberof PresetCreate
     */
    config: string;
    /**
     * The name of the environment preset.
     * @type {string}
     * @memberof PresetCreate
     */
    name: string;
    /**
     * The ID of the user who owns this environment preset.
     * @type {string}
     * @memberof PresetCreate
     */
    userId: string;
}

/**
 * Check if a given object implements the PresetCreate interface.
 */
export function instanceOfPresetCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "config" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function PresetCreateFromJSON(json: any): PresetCreate {
    return PresetCreateFromJSONTyped(json, false);
}

export function PresetCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresetCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': json['config'],
        'name': json['name'],
        'userId': json['userId'],
    };
}

export function PresetCreateToJSON(value?: PresetCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': value.config,
        'name': value.name,
        'userId': value.userId,
    };
}

