/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Model for updating an existing entity.  `id`, audit fields (`createdAt`, `updatedAt`) and `userId` (hash key) are excluded from update.
 * @export
 * @interface PresetUpdate
 */
export interface PresetUpdate {
    /**
     * Configuration details for the entity.
     * @type {string}
     * @memberof PresetUpdate
     */
    config?: string;
    /**
     * Name of the entity.
     * @type {string}
     * @memberof PresetUpdate
     */
    name?: string;
}

/**
 * Check if a given object implements the PresetUpdate interface.
 */
export function instanceOfPresetUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PresetUpdateFromJSON(json: any): PresetUpdate {
    return PresetUpdateFromJSONTyped(json, false);
}

export function PresetUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresetUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': !exists(json, 'config') ? undefined : json['config'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PresetUpdateToJSON(value?: PresetUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': value.config,
        'name': value.name,
    };
}

