/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Query
 */
export interface Query {
    /**
     * 
     * @type {Date}
     * @memberof Query
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Query
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Query
     */
    queryText: string;
    /**
     * 
     * @type {string}
     * @memberof Query
     */
    responseText?: string;
    /**
     * 
     * @type {number}
     * @memberof Query
     */
    topK: number;
    /**
     * 
     * @type {string}
     * @memberof Query
     */
    userId: string;
}

/**
 * Check if a given object implements the Query interface.
 */
export function instanceOfQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "queryText" in value;
    isInstance = isInstance && "topK" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function QueryFromJSON(json: any): Query {
    return QueryFromJSONTyped(json, false);
}

export function QueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Query {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'id': json['id'],
        'queryText': json['queryText'],
        'responseText': !exists(json, 'responseText') ? undefined : json['responseText'],
        'topK': json['topK'],
        'userId': json['userId'],
    };
}

export function QueryToJSON(value?: Query | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'id': value.id,
        'queryText': value.queryText,
        'responseText': value.responseText,
        'topK': value.topK,
        'userId': value.userId,
    };
}

