/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryChunkMatchCreate
 */
export interface QueryChunkMatchCreate {
    /**
     * The ID of the chunk.
     * @type {string}
     * @memberof QueryChunkMatchCreate
     */
    chunkId: string;
    /**
     * The ID of the query.
     * @type {string}
     * @memberof QueryChunkMatchCreate
     */
    queryId: string;
    /**
     * The rank of the chunk for the given query.
     * @type {number}
     * @memberof QueryChunkMatchCreate
     */
    rank: number;
    /**
     * The relevance score of the chunk for the given query.
     * @type {number}
     * @memberof QueryChunkMatchCreate
     */
    score: number;
}

/**
 * Check if a given object implements the QueryChunkMatchCreate interface.
 */
export function instanceOfQueryChunkMatchCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chunkId" in value;
    isInstance = isInstance && "queryId" in value;
    isInstance = isInstance && "rank" in value;
    isInstance = isInstance && "score" in value;

    return isInstance;
}

export function QueryChunkMatchCreateFromJSON(json: any): QueryChunkMatchCreate {
    return QueryChunkMatchCreateFromJSONTyped(json, false);
}

export function QueryChunkMatchCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryChunkMatchCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chunkId': json['chunkId'],
        'queryId': json['queryId'],
        'rank': json['rank'],
        'score': json['score'],
    };
}

export function QueryChunkMatchCreateToJSON(value?: QueryChunkMatchCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chunkId': value.chunkId,
        'queryId': value.queryId,
        'rank': value.rank,
        'score': value.score,
    };
}

