/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryCreate
 */
export interface QueryCreate {
    /**
     * The text of the query.
     * @type {string}
     * @memberof QueryCreate
     */
    queryText: string;
    /**
     * The response text associated with the query.
     * @type {string}
     * @memberof QueryCreate
     */
    responseText?: string;
    /**
     * The number of top results to retrieve.
     * @type {number}
     * @memberof QueryCreate
     */
    topK: number;
    /**
     * The ID of the user making the query.
     * @type {string}
     * @memberof QueryCreate
     */
    userId: string;
}

/**
 * Check if a given object implements the QueryCreate interface.
 */
export function instanceOfQueryCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "queryText" in value;
    isInstance = isInstance && "topK" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function QueryCreateFromJSON(json: any): QueryCreate {
    return QueryCreateFromJSONTyped(json, false);
}

export function QueryCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'queryText': json['queryText'],
        'responseText': !exists(json, 'responseText') ? undefined : json['responseText'],
        'topK': json['topK'],
        'userId': json['userId'],
    };
}

export function QueryCreateToJSON(value?: QueryCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'queryText': value.queryText,
        'responseText': value.responseText,
        'topK': value.topK,
        'userId': value.userId,
    };
}

