/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryChunkMatch
 */
export interface QueryChunkMatch {
    /**
     * 
     * @type {string}
     * @memberof QueryChunkMatch
     */
    chunkId: string;
    /**
     * 
     * @type {string}
     * @memberof QueryChunkMatch
     */
    queryId: string;
    /**
     * 
     * @type {number}
     * @memberof QueryChunkMatch
     */
    rank: number;
    /**
     * 
     * @type {number}
     * @memberof QueryChunkMatch
     */
    score: number;
}

/**
 * Check if a given object implements the QueryChunkMatch interface.
 */
export function instanceOfQueryChunkMatch(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chunkId" in value;
    isInstance = isInstance && "queryId" in value;
    isInstance = isInstance && "rank" in value;
    isInstance = isInstance && "score" in value;

    return isInstance;
}

export function QueryChunkMatchFromJSON(json: any): QueryChunkMatch {
    return QueryChunkMatchFromJSONTyped(json, false);
}

export function QueryChunkMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryChunkMatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chunkId': json['chunkId'],
        'queryId': json['queryId'],
        'rank': json['rank'],
        'score': json['score'],
    };
}

export function QueryChunkMatchToJSON(value?: QueryChunkMatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chunkId': value.chunkId,
        'queryId': value.queryId,
        'rank': value.rank,
        'score': value.score,
    };
}

