/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Model for updating an existing query.
 * @export
 * @interface QueryUpdate
 */
export interface QueryUpdate {
    /**
     * The text of the query.
     * @type {string}
     * @memberof QueryUpdate
     */
    queryText?: string;
    /**
     * The response text for the query.
     * @type {string}
     * @memberof QueryUpdate
     */
    responseText?: string;
    /**
     * The number of top results to retrieve.
     * @type {number}
     * @memberof QueryUpdate
     */
    topK?: number;
}

/**
 * Check if a given object implements the QueryUpdate interface.
 */
export function instanceOfQueryUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QueryUpdateFromJSON(json: any): QueryUpdate {
    return QueryUpdateFromJSONTyped(json, false);
}

export function QueryUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'queryText': !exists(json, 'queryText') ? undefined : json['queryText'],
        'responseText': !exists(json, 'responseText') ? undefined : json['responseText'],
        'topK': !exists(json, 'topK') ? undefined : json['topK'],
    };
}

export function QueryUpdateToJSON(value?: QueryUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'queryText': value.queryText,
        'responseText': value.responseText,
        'topK': value.topK,
    };
}

