/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleCreate
 */
export interface RoleCreate {
    /**
     * Optional description
     * @type {string}
     * @memberof RoleCreate
     */
    description?: string;
    /**
     * Role name
     * @type {string}
     * @memberof RoleCreate
     */
    name: string;
}

/**
 * Check if a given object implements the RoleCreate interface.
 */
export function instanceOfRoleCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function RoleCreateFromJSON(json: any): RoleCreate {
    return RoleCreateFromJSONTyped(json, false);
}

export function RoleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
    };
}

export function RoleCreateToJSON(value?: RoleCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
    };
}

