/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleUpdate
 */
export interface RoleUpdate {
    /**
     * Optional description to update
     * @type {string}
     * @memberof RoleUpdate
     */
    description?: string;
    /**
     * Role name to update
     * @type {string}
     * @memberof RoleUpdate
     */
    name: string;
}

/**
 * Check if a given object implements the RoleUpdate interface.
 */
export function instanceOfRoleUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function RoleUpdateFromJSON(json: any): RoleUpdate {
    return RoleUpdateFromJSONTyped(json, false);
}

export function RoleUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
    };
}

export function RoleUpdateToJSON(value?: RoleUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
    };
}

