/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sequence
 */
export interface Sequence {
    /**
     * Optional description
     * @type {number}
     * @memberof Sequence
     */
    currentValue?: number;
    /**
     * Role name
     * @type {string}
     * @memberof Sequence
     */
    sequenceName: string;
}

/**
 * Check if a given object implements the Sequence interface.
 */
export function instanceOfSequence(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sequenceName" in value;

    return isInstance;
}

export function SequenceFromJSON(json: any): Sequence {
    return SequenceFromJSONTyped(json, false);
}

export function SequenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sequence {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentValue': !exists(json, 'current_value') ? undefined : json['current_value'],
        'sequenceName': json['sequenceName'],
    };
}

export function SequenceToJSON(value?: Sequence | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current_value': value.currentValue,
        'sequenceName': value.sequenceName,
    };
}

