/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionCreate
 */
export interface SessionCreate {
    /**
     * The date and time when the session expires.
     * @type {Date}
     * @memberof SessionCreate
     */
    expiresAt: Date;
    /**
     * The session token.
     * @type {string}
     * @memberof SessionCreate
     */
    token: string;
    /**
     * The ID of the user associated with this session.
     * @type {string}
     * @memberof SessionCreate
     */
    userId: string;
}

/**
 * Check if a given object implements the SessionCreate interface.
 */
export function instanceOfSessionCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "expiresAt" in value;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function SessionCreateFromJSON(json: any): SessionCreate {
    return SessionCreateFromJSONTyped(json, false);
}

export function SessionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expiresAt': (new Date(json['expiresAt'])),
        'token': json['token'],
        'userId': json['userId'],
    };
}

export function SessionCreateToJSON(value?: SessionCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expiresAt': (value.expiresAt.toISOString()),
        'token': value.token,
        'userId': value.userId,
    };
}

