/* tslint:disable */
/* eslint-disable */
/**
 * SRE DynamoDB Table definition - OpenAPI 3.0
 * DynamoDB Data doc for SRE Project
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionUpdate
 */
export interface SessionUpdate {
    /**
     * The expiration date and time of the token.
     * @type {Date}
     * @memberof SessionUpdate
     */
    expiresAt?: Date;
    /**
     * The authentication token.
     * @type {string}
     * @memberof SessionUpdate
     */
    token?: string;
}

/**
 * Check if a given object implements the SessionUpdate interface.
 */
export function instanceOfSessionUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SessionUpdateFromJSON(json: any): SessionUpdate {
    return SessionUpdateFromJSONTyped(json, false);
}

export function SessionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expiresAt': !exists(json, 'expiresAt') ? undefined : (new Date(json['expiresAt'])),
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function SessionUpdateToJSON(value?: SessionUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expiresAt': value.expiresAt === undefined ? undefined : (value.expiresAt.toISOString()),
        'token': value.token,
    };
}

